title: тест
guititle: Продажа
show: false
tax: 0.0
worth:
  §aПшеница: 6.0
  §aСемена пшеницы: 0.4
  §aПризрачный уголь: 0.4
  §aУголь: 20.0
  §aЗаписка: 1.0
  §aКнига с заклинаниями: 30.0
  §aОстанки солдата: 1.4
  §aСердце предводителя: 40.0
  §aОсколок: 1.8
  §aЧастицы: 50.0
  §aТортик с плесенью: 60.0
  §aМука 3 сорт: 2.2
  §aНелепость: 2.2
  §aШар предсказаний: 70.0
  §aСлезы: 3.0
  §aАдские семена: 80.0
  §aКлейкая слизь: 80.0
  §aОстанки зараженного: 3.0
  §aМясо медведя: 90.0
  §aШкура волка: 2.4
  §aОстанки душ: 2.8
  §aДуша: 100.0
  §aЗуб дракона: 4.0
  §aМешок со специями: 110.0
  §aЛапка клеща: 4.2
  §aСкорлупа: 120.0
  §aЖало: 5.0
  §aСоты: 140.0
  §aОстанки стража: 5.8
  §aБинты с мумии: 150.0
